name: Deploy Built Site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: npm install and build
        working-directory: code
        run: |
          npm install
          npm run build -- --public-url /fox-tamagotchi/
      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v1.4.0
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        with:
          build_dir: fox-tamagotchi/dist
